import type { Metadata } from 'next';
import '@/app/css/global.css';
import { geometria } from '@/shared/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geometria.className}>{children}</body>
    </html>
  );
}
